// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/contact-us": {
    params: {};
  };
  "/book-tour": {
    params: {};
  };
  "/booking": {
    params: {};
  };
  "/kigali-experiences": {
    params: {};
  };
  "/tours": {
    params: {};
  };
  "/tours/:tourId": {
    params: {
      "tourId": string;
    };
  };
  "/auth/login": {
    params: {};
  };
  "/auth/request": {
    params: {};
  };
  "/admin/dashboard": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/contact-us" | "/book-tour" | "/booking" | "/kigali-experiences" | "/tours" | "/tours/:tourId" | "/auth/login" | "/auth/request" | "/admin/dashboard";
  };
  "./layouts/default.tsx": {
    id: "layouts/default";
    page: "/" | "/contact-us" | "/book-tour" | "/booking" | "/kigali-experiences" | "/tours" | "/tours/:tourId";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/contactUs.tsx": {
    id: "routes/contactUs";
    page: "/contact-us";
  };
  "routes/bookTour.tsx": {
    id: "routes/bookTour";
    page: "/book-tour";
  };
  "routes/booking.tsx": {
    id: "routes/booking";
    page: "/booking";
  };
  "routes/kigaliExperiences.tsx": {
    id: "routes/kigaliExperiences";
    page: "/kigali-experiences";
  };
  "routes/tours.tsx": {
    id: "routes/tours";
    page: "/tours";
  };
  "routes/tours.$tourId.tsx": {
    id: "routes/tours.$tourId";
    page: "/tours/:tourId";
  };
  "./layouts/auth/layout.tsx": {
    id: "layouts/auth/layout";
    page: "/auth/login" | "/auth/request";
  };
  "routes/auth.login.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/auth.request.tsx": {
    id: "routes/auth.request";
    page: "/auth/request";
  };
  "./layouts/admin/layout.tsx": {
    id: "layouts/admin/layout";
    page: "/admin/dashboard";
  };
  "routes/admin.dashboard.tsx": {
    id: "routes/admin.dashboard";
    page: "/admin/dashboard";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "layouts/default": typeof import("./src/./layouts/default.tsx");
  "routes/home": typeof import("./src/routes/home.tsx");
  "routes/contactUs": typeof import("./src/routes/contactUs.tsx");
  "routes/bookTour": typeof import("./src/routes/bookTour.tsx");
  "routes/booking": typeof import("./src/routes/booking.tsx");
  "routes/kigaliExperiences": typeof import("./src/routes/kigaliExperiences.tsx");
  "routes/tours": typeof import("./src/routes/tours.tsx");
  "routes/tours.$tourId": typeof import("./src/routes/tours.$tourId.tsx");
  "layouts/auth/layout": typeof import("./src/./layouts/auth/layout.tsx");
  "routes/auth.login": typeof import("./src/routes/auth.login.tsx");
  "routes/auth.request": typeof import("./src/routes/auth.request.tsx");
  "layouts/admin/layout": typeof import("./src/./layouts/admin/layout.tsx");
  "routes/admin.dashboard": typeof import("./src/routes/admin.dashboard.tsx");
};